### ISSUE TITLE
Easter egg event in the initial cave doesn't happen

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#1342]
# 環境 Environment

* OS version: macOS 10.14.5
* Elona foobar verision: develop

# 詳細 Details

When you say to Lomias "Get out of my house!" after killing Larnneire, Lomias gets angry and hostile against you. It exists in vanilla, but does not happen due to a bug. In foobar, it has been fixed before, but now (maybe since Lua-based dialog system was introduced) come to occur again.

![image](https://user-images.githubusercontent.com/36858341/58747326-a472ca00-84a4-11e9-8142-1e9c99ffca29.png)

# 再現方法 How to reproduce

1. Kill Larnneire.
2. Talk to Lomias.
3. Say to him, "Get out of my house!"

**Comment by Vorlent** [comment]
https://github.com/ElonaFoobar/ElonaFoobar/blob/develop/runtime/mod/core/data/dialog/unique/lomias.lua#L200 doesn't return nil

Larnneire still exists on the map with negative hp. 

A potential fix would be to check if Larnneire is dead:

```
if larnneire == nil or not Chara.is_alive(larnneire) then
```

However I didn't submit a PR because I think something more fundamental is broken. Why is Larnneire still on the map if she is dead? Even if you leave the map and come back her "ghost" is still there.

**Comment by ki-foobar** [comment]
@Vorlent

Your fix is correct.

>  Why is Larnneire still on the map if she is dead? Even if you leave the map and come back her "ghost" is still there.

It is a right behavior, not a bug. In Elona, dead  characters who will resurrect after some 3 days remain in the map as "ghosts". Because Larnneire (and Lomias) will resurrect even if she is killed, her data still exist in `cdata`.

**Comment by ki-foobar** [comment]
Fixed by #1362
