### ISSUE TITLE
Mad Millionaire exploit

### ISSUE THREAD

**Issue by EvgenijM86** [elonafoobar/elonafoobar#1480]
Mad Millionaire gives something like 0-10% (~5% on average) of your current money supply. Bloody thieves subtracts even more than that, so with those 2 events you are in the negative on average. But if you stack luck (starting traits + cheap mica equipment) you can prevent bloody thieves event a lot of the times. And this gives accelerated growth of your money if you just wait on some map except your home (it is slower on the world map). This event is based on the time that has been passed, so you minimize your speed to 10 by overburdening yourself with extra weight and not sleeping for a long time. Now you can pass time 7x faster and those events will trigger one after another in like less than a minute of you holding "next turn" button. If you started with 200 000 gp you can reach a 1 000 000 gp by just waiting it out for 1-2 hours in real time (you will never get this much money by doing quests for 1-2 hours). And it continue like this without any limit - you can wait a couple of more hours and turn those 1 million into 4 millions, then 4 into 16 et.c.

**Comment by ki-foobar** [comment]
This exploit is not so big problem in vanilla because the amount of money you earn by the event in vanilla has the upper limit. `rnd()` function in HSP, the language vanilla is written in, generates random number from `0` to `2^15-1`. Such a small amount of money cannot break the game balance. In foobar, however, the upper limit of the function `rnd()`, reimplemented in C++, is `2^31-1` in order to maximize extensibility of mods.
I think that the random number generation in foobar should be reimplemented and behave as vanilla. When the change is done, the mad millionaire issue will also fixed.
