### ISSUE TITLE
[0.7.5] Amibiguous error message when version name in directory and version in mod.json is different

### ISSUE THREAD

**Issue by YukariTea** [elonafoobar/elonafoobar#1763]
Steps to reproduce:

1. Enable a mod in-game
2. Close the game
3. Change the version number in the directory name of the mod
4. Open the game

Alternative steps to reproduce
1. Enable a mod in-game
2. Exit the game
3. Open the game
4. Edit the mod's `mod.json` and change the version number.
5. Exit and re-enter the mod menu
6. Toggle on and off the mod
7. Exit the game
8. Open the game
9. Toggle on the mod
10. Exit the game
11. Open the game

The ambiguous error message given is "expect any JSON5 value, but actually \<EOF\>".

**Comment by ki-foobar** [comment]
In v0.7.5, both of file open error and JSON5 syntax error are reported as JSON5 error as described. It was fixed by the commit: 0fa817e5015e50e546f818e2988bf25e04251a6b

New error message:
> failed to open \<path to elonafoobar\>/mod/\<mod\>-\<version\>/mod.json to read

It reports that a mod folder with the version specified by `profile/<profile name>/mods.json` does not exist in `mod` directory.
