### ISSUE TITLE
[Request] Mod versioning enhancements

### ISSUE THREAD

**Issue by YukariTea** [elonafoobar/elonafoobar#1764]
- [ ] Remove version field from mods.json

Mods are already required to have their root directory name match the version field, so there isn't a really a point of specifying it again. It also introduces the possibility of errors for a developer to change the version number in one place, but not the other.

- [ ] Allow arbitrary number of versioning digits

Currently the system only supports up to three digits. Adding another like "0.7.5.0" will produce an error.

**Comment by ki-foobar** [comment]
> Remove version field from mods.json

`version` field in `mod.json` is required to identify its version especially for mods which are published in GitHub or other hosting sites. Such mod's version cannot be determined by its repository URL (It is very annoying to change repo name every release, of course).



> It also introduces the possibility of errors for a developer to change the version number in one place, but not the other.

Yes, it is error-prone. This problem must be addressed by any means later or sooner. My rough idea is to separate mods that one are developing from mods that one downloads, and allow the former to include no version identifier in the folder name.



> Allow arbitrary number of versioning digits
> Currently the system only supports up to three digits. Adding another like "0.7.5.0" will produce an error.

It is intentional. Elona foobar's mod version number follows [Semantic Versioning 2.0.0](https://semver.org/spec/v2.0.0.html). The specification disallows arbitrary number of versioning digits.

The current implementation to handle Semantic Versioning is not complete so that it cannot correctly deal with [pre-release specifiers](https://semver.org/spec/v2.0.0.html#spec-item-9) and [build identifiers](https://semver.org/spec/v2.0.0.html#spec-item-10) just because there are few foobar mods. It is welcome to fix the issue.

**Comment by YukariTea** [comment]
> version field in mod.json is required to identify its version especially for mods which are published in GitHub or other hosting sites

I had not considered this. That is a good point. The suggested approach of ignoring version for development versions works well.

> The specification disallows arbitrary number of versioning digits.

I see. It is good to follow a consistent specification, but I think mod authors should also have the freedom to choose any versioning system they wish to use. There are Elona forks that do not follow semantic versioning. If mod authors are developing a mod based on a fork, they may choose to match version numbers with a fork's number alongside their own version number to indicate compatibility, especially if the the fork does not move development to Elona foobar (an example is Elona Plus forks like Custom). Complete freedom is not possible, since allowing arbitrary strings as version numbers would break dependencies for any operator other than "=", but allowing arbitrary numbers of versioning digits should still allow >=, <= to function. If an operator like the node.js ^ operator (latest version with compatible API) exists, it will not break, but no longer has any meaning. This has a downside that mod authors will no longer be able to make assumptions about the versioning of a mod. Let me know what you think, it might not be good to allow arbitrary versioning digits after all.

**Comment by ki-foobar** [comment]
> If mod authors are developing a mod based on a fork, they may choose to match version numbers with a fork's number alongside their own version number to indicate compatibility, especially if the the fork does not move development to Elona foobar (an example is Elona Plus forks like Custom).

It can be represented as [build metadata of SemVer](https://semver.org/#spec-item-10) like version `1.2.3+plus.2.00`. This approach breaks no SemVer's rules, and makes modders to include corresponding version information of Elona variant in version spec.
