### ISSUE TITLE
[Discuss] Config file format

### ISSUE THREAD

**Issue by ki-foobar** [ElonaFoobar/ElonaFoobar#300]
We should decide configuration file format until beta release. Basically, all options should be changed from option menu in game, but we should provide a human-readable configuration file too.
In addition, we will use this format for other files, such as resource definition files.

We are using JSON for `config.json`, but I don't like it because it forces me to write *strictly*(No trailing comma! No comment!)
JSON is machine-readable/writable, but not human-readable/writable.

# JSON

## Advantages

- Many libraries.

## Disadvantages

- Hard to write correctly for non-engineers.
  - Doesn't allow trailing comma.
  - Can't write any comments.

# YAML

## Advantages

- Flexible notations.

## Disadvantages

- Indentation-based syntax seems to be hard to write for non-engineers.

# INI

## Advantages

- Simple. Very simple.

## Disadvantages

- Too simple.
- No strict specification.

# TOML

## Advantages

- Simple and flexible.

## Disadvantages

- Fewer libraries than others.

# XML

## Disadvantages

- Never human-readable/writable.

# Lua script

## Advantages

- We are using Lua for MOD.
- Most flexible, of course.

## Disadvantages

- Too flexible because it is a true programming language.
  - It makes hard to copy&paste other's config file.

# Elona config format

## Advantages

- Familiar to Elona players.

## Disadvantages

- No specification, no library.
- We should not reinvent the wheel.

# Others?

**Comment by Ruin0x11** [comment]
I was thinking about different specification languages for mods mostly, but the options config could be discussed too.

I was thinking for data that isn't anything more than simple key-value pairs (like localizations), an INI-like config format could suffice. Boost provides one through `<boost/property_tree/ini_parser.hpp>`. Beyond that it would be better to have a config syntax with some notion of typing.

JSON is kind of annoying to write. It doesn't seem like a good config language, but more like a data specification language. But even when specifying data I would rather not have the syntax and lack of comments get in the way.

On the subject of Lua, I was also thinking about how players can apply mod changes to some group of monsters. It might be nice to be able to do so programatically in Lua for complex usecases, and otherwise use a simpler declaration format for quick and easy creation. Since we're using Lua anyway we won't need to pull in another dependency if we do so. Using Lua for configuration options is definitely overkill, though.

YAML in its full form is far too complex, and even simplified the indentation could get be hard to get used to.

TOML seems to be most similar to the original key-value format without being INI and having types. However, it would require another dependency. Also, the syntax for nested tables is somewhat confusing. I have successfully implemented object prototyping using TOML before, though.

**Comment by Ruin0x11** [comment]
Personally, I would vouch for TOML. It has typing and is similar enough to the original file format. All static data can be declared through TOML, and everything else in Lua.

**Comment by Ruin0x11** [comment]
I recently discovered [HCL](https://github.com/hashicorp/hcl) and [HIL](https://github.com/hashicorp/hil). HCL is purely for data and HIL is for interpolating function calls inside strings. A strict subset of the two should serve the required purposes.

**Comment by Ruin0x11** [comment]
I wrote a parser for HCL (here)[https://github.com/Ruin0x11/microhcl]. Here is what the new config would look like:

``` hcl
general {
  language = "japanese" # "japanese", "english" or "ask"
  alert_wait = 50 # txt wait when important things happen
  anime_wait = 20 # animation wait (0 = disable all animations)
  story = false
  extra_race = true
  start_run = 2

  # The saved game in the folder will be automatically loaded after launching the game.
  # (Use a folder name under the \save folder. ie."sav_player" )
  default_save_folder = "sav_player"
}

gameplay {
  ignore_dislike = false
}

screen {
  fullscreen = false
}

font {
  # Please use monospace fonts like Lucida Console font.
  japanese = "ＭＳ ゴシック"
  english = "Courier New"
}
```

I also prototyped some data definitions, for creating custom characters/items.

```hcl
character "my_character" {
  base = "core.base_character" // optional, inherits properties from this character

  level = 20
  race = "norland"
  class = "gunner"
  has_random_name = true
  original_relationship = -3
  normal_actions = ["core.action.1", "core.action.2"]
  special_actions = ["core.special_action.1"]
  color = 17
  resistances {
    _51 = 50
    _50 = 500
  }
  flags = ["is_quick_tempered"]

  spawn {
    rarity = 2000
    coefficient = 400
  }
}
```

```hcl
item "my_potion" {
  id = "my_neat_potion"
  name = "locale.my_potion" // defined in locale/*/something.hcl
  description = "locale.my_potion_desc" // defined in locale/*/something.hcl
  image = 405 // "core.potion"
  value = 500
  weight = 1500

  more {
    // maybe make this optional, although I want the convention to be
    // that only sections are optional, to increase uniformity
    light = 0
    has_random_name = true
    color = 1 // TODO make a random color flag?
  }

  // optional section if you want the item to show up in dungeons and the like
  // otherwise this item will only be available by spawning from scripts
  spawn {
    rarity = 700000
    coefficient = 100
  }

  category = 52000 // TODO needs fixing up
  subcategory = 99999 // TODO needs fixing up

  // some things are optional depending on item type.
  drink {
    effect = "my_mod.my_magic" // expects magic to have been defined somewhere else
    power = 100
  }
}
```

Does this sound like a good direction to take? If there are missing features I could modify the parser to include them.

**Comment by Ruin0x11** [comment]
Config format has been more or less migrated.
