### ISSUE TITLE
Store the last quicksave in memory to reduce load times

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#433]
# Details
It would be nice to have an option to turn on quicksave hotloading by storing the last quicksave in memory. Then the memory could just be copied over. This comes at the expense of memory, but it could be made into an optional feature.

It would require the whole save state to be encapsulated well enough so this becomes easily doable.

**Comment by ki-foobar** [comment]
Most of other variants tried to improve loading performance too.

From omake's README:
> Implemented feature so save data loads only the required files. This speeds up the data load process.

Your proposal is interesting, but I think it would be better to implement this feature first, and then implement storing the whole state.

I have not measured, but according to other variants' authors, it takes much time to copy files from save/sav_XXX to tmp/ directory.

I am currently fixing known bugs since vanilla.
After all bugs are fixed, I will investigate this feature that speeds up loading implemented in omake and port it to Foobar.

**Comment by Ruin0x11** [comment]
Agreed that we should fix bugs first. It's just nice having a known repository of new features to add. This is for looking ahead.

**Comment by Ruin0x11** [comment]
Closing in favor of #444.
