### ISSUE TITLE
Support custom resolutions

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#508]
# Details
Support resolutions other than 800x600 without stretching of the graphics.

# Implementation note
There are multiple ways of going about this.
1. Choose from a supported list of standard resolutions.
2. Allow the user to resize the game window arbitrarily.

# Variants having this feature
Elona+

**Comment by ki-foobar** [comment]
This feature had been implemented since vanilla.
I have disabled it before because it crashed Elona for some reason(I forget the reason unfortunately).

I prefer the first choice because the current GUI codebase has not been organized, so the other looks like difficult to me. In addition, since the former had been implemented since vanilla, I guess we can implement it easily with a little change.

**Comment by Ruin0x11** [comment]
I added the feature, although there's a strange bug with the text window.

![https://my.mixtape.moe/wmvzcs.png](https://my.mixtape.moe/wmvzcs.png)

**Comment by Ruin0x11** [comment]
Turns out the temporary buffer texture was too small to hold the whole text window region, so it seemed to get stretched.
