### ISSUE TITLE
rnd() being called with max <= 0 at certain points

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#536]
# Environment

* OS version: Windows 10
* Elona Foobar verision: `develop`

# Details
A user reported this issue. Just after starting a performance, this happens:

![](https://media.discordapp.net/attachments/418060729891946497/455389863550648340/7ac70a008683861d.JPG)

Then after casting Incognito, it happens again:

![](https://cdn.discordapp.com/attachments/418060729891946497/455401029333155851/cdfa329d16a4fec4.JPG)

The black background is normal.

I couldn't get this issue to reproduce in my environment.

# Cause
It appears `rnd` is being called with `max <= 0` in both cases. There are apparently places in the code where this can still happen if `max` is an integer variable.

# Solution
Make `rnd` with `max <= 0` return `true` instead of crashing.

**Comment by ki-foobar** [comment]
I tried to call `rnd(0)` in HSP(ver. 3.5). HSP just reported error.

```
#Error 19 in line 2
--> Divide by 0
```

It implies that there are something wrong in our C++ code because this error does not happen in vanilla and other variants.

We should change not to throw exception when `rnd` is passed `0` or negative for careless Lua MOD, but detect the place calling `rnd(0)` at the same time.

**Comment by ki-foobar** [comment]
The cause was detected, overflow.

# How to reproduce

1. Make your level 99 or more.
2. Cast some spell.

# Details

```
In skillexp():

LExp = Character level experience
ReqExp = Required experience until next character level
Exp = Experience you gained just now by casting spell

LExp = rnd(ReqExp * Exp / 1000 / (CharacterLevel + 5) + 1)
```

`ReqExp` reaches `1,000,000` at 99 character level. If `Exp` is greater than 21, `ReqExp * Exp` gets over `2^31-1`.
As a result, `rnd` function receives negative number, reporting assertion error.

c.f. HSP `rnd` causes error with `0`, but if negative number is passed to, returns 0 without error.
