### ISSUE TITLE
Enable commit rebasing

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#616]
# Details
It would be nice to have the ability to run `Rebase and Merge` when merging pull requests so the commit history is clean. Right now it is rather unreadable with half of the recent commits being merges.

**Comment by ki-foobar** [comment]
I do not have plan to allow "rebase and merge".

Generally speaking, resolving conflicts in rebasing is harder than in merging because you need resolve conflict in more commits. It could increase main contributors' work. Especially, in OSS, those who send a pull request not always react out review. Even if they do not react, we would sometimes want to merge the pull request. In this case, we need fix something wrong or resolve conflict, but it is harder for us than for the contributor. Rebasing, I think, makes it even harder in that we have to see their WIP commits.

As for small pull request, "rebase and merge" is efficient, even considering above reasons, but I believe complex rule makes it difficult to manage open source project. In this repository, just "Create a merge commit" in all cases.

**Comment by Ruin0x11** [comment]
Ok, that's fine.
